### PR TITLE
please publish the updated version to npm

### PR DESCRIPTION
**Pull request by ssured**

### CODE REVIEW

**Comment by ssured** [comment]
I got bitten today by my own PR #8 ... Cost me two hours to debug. Because the project is in coffee checking out master is not working in a JS project. It would be nice to push the new features as new versions. Thanks!

**Comment by edi9999** [comment]
done (v.0.3.4)

**Comment by ssured** [comment]
awesome, thanks!

**Comment by ssured** [comment]
I think you still need to push from your local repo to github; right now package.json is still on 0.3.3. NPM seems fine though

**Pull request closed without merging**
