### PR TITLE
Support for PPTX documents

### PR DESCRIPTION
**Pull request by MaxRcd**
Hello,

I reworked and I think improved the work done on Pull Request #12 last year.

I needed to be able to set the centering option for each image and not globally so I introduced the tag {%%image} that is working on DOCX and PPTX documents.

When enabled PPTX centering will centers the image in the middle of the parent cell (vertically and horizontally).

The test won't work for now because test utils don't support pptx. I'm about to open a PR for that on docxtemplater repository.

Regards,
Maxime

Note: I'm a newcomer (pull request and ES6), please be kind but say it.

### CODE REVIEW

**Comment by edi9999** [comment]
Sorry for not looking into it, somehow I didn't get notifications for issues in the last months.

**Comment by MaxRcd** [comment]
Hi Edi9999,

No problem I'm still here.
I closed/reopened the PR to trigger Travis CI build.

There is a problem with word documents, one of the tests fails, but I don't remember to have seen this issue with my local version. Have to check that.

Regards,
Maxime

**Comment by edi9999** [comment]
I have integrated your changes manually into master after adding a few commits myself : 

https://github.com/open-xml-templating/docxtemplater-image-module/commit/bbd2cf6fa3a300acff08d5d8e19e122e8cf4656e

A huge thanks for your contribution, you did a great job !n

**Comment by MaxRcd** [comment]
Great news ! You are welcome.
Thanks for merging

**Pull request closed without merging**
