### PR TITLE
Added Basic PPTX Image Support

### PR DESCRIPTION
**Pull request by amorri40**

### CODE REVIEW

**Comment by edi9999** [comment]
Hi, 

Thanks for the PR. I think only one thing is not good for the merge: the extra dependency for node XML. There is already a library for that that's in the package.Json, and you should already be able to use this with DocUtils.str2Xml and Xml2str

**Comment by edi9999** [comment]
Up can you update the script by using those methods ?

**Comment by adamclerk** [comment]
@amorri40 will you be resolving this soon? I'd be happy to take of the PR and resolve the issues if you're not.

cc @edi9999

**Comment by amorri40** [comment]
You are more than welcome to resolve the issue :)

**Comment by danmo** [comment]
would love to see this one as it's a pretty needed feature

**Comment by edi9999** [comment]
Closed in favor of #74

**Pull request closed without merging**
