### PR TITLE
Pass tag data to getSizeFromData

### PR DESCRIPTION
**Pull request by daz**

### CODE REVIEW

**Comment by edi9999** [comment]
Here you're passing the name instead of the value (eg use imgData instead). You can pass tag as the third parameter if you want

**Comment by daz** [comment]
Just curious how we could switch on `imgData`?

I'm using this so I can use the same image multiple times at different sizes...

```coffee
  imageModule.getSizeFromData = (imageData, tagData) ->
    switch tagData
      when 'HeaderLogo'
        sizeToFit imageData, '300x25'
      when 'CoverLogo'
        sizeToFit imageData, '600x300'
      else
        imageSize imageData
```

**Comment by edi9999** [comment]
Example:

Template:

{IMG}

In your json:

```
{IMG:{path:'/var/IMG.png',size:[100,300]}}
```

And getImageFromData returns fs.readfile(imgData.path)

And getSizeFromData returns imgData.size

**Comment by edi9999** [comment]
The thing is that tag keys need to be strings, but tag values can contain more information, such as the size

**Pull request closed without merging**
